package PageObjects.Elements.Task;

/**
 * Created by Piotr Majewski on 2017-05-16.
 */
public enum TaskButton {
    ACCEPT, REJECT, REGUEST_NEW_DEADLINE, INSTRUCTION, PROCESSING, TRANSLATION_TASK_REF,
    ASSIGN_TO_TRANSLATOR, IN_PROGRESS, SELF_QA, COMPLETED_TRANSLATOR, EXECUTE, ASSIGN_TO_EDITOR,
    COMPLETED_EDITOR, COMMENT;
}
